
volumes:
  pg_data:
  hf_cache:
services:
  db:
    ports: 
      - "5432:5432" 
    image: pgvector/pgvector:pg16
    volumes:
     - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
  api:
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env 
    volumes:
      - hf_cache:/root/.cache/huggingface
    environment:
      POSTGRES_HOST: db 
      

 
