from psycopg_pool import ConnectionPool 
from pgvector.psycopg import register_vector 
from dotenv import load_dotenv 
import os
import hashlib
import psycopg
load_dotenv() 
host = os.getenv("POSTGRES_HOST","localhost")
pw = os.getenv("POSTGRES_PASSWORD")
conn_string = f"postgresql://postgres:{pw}@{host}:5432/postgres"

def create_pool(conn_string) : 
    return ConnectionPool(conn_string,min_size=2,max_size=5 , configure=register_vector )
def get_user_chunks(pool , user_id):
    # borrows a connection only for this query, then returns it to the pool
    with pool.connection() as conn :
        return conn.execute("SELECT id,chunk_text FROM chunks WHERE user_id=%s ORDER BY id",(user_id,),).fetchall()


def search_user_vectors(pool , user_id , question_vector , k ):
    with pool.connection() as conn :
        return conn.execute("SELECT  id , chunk_text FROM chunks WHERE user_id=%s ORDER BY chunk_vector <=> %s LIMIT %s",(user_id,question_vector,k )).fetchall()
    

def init_schema(conn_string) :
    # runs once at app startup, BEFORE the pool is created (the pool registers the vector type on every connection,
    # which fails if the extension doesn't exist yet). Every statement is a no-op when the thing already exists.
    with psycopg.connect(conn_string , autocommit=True) as conn :
        conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
        # user_id is generated by the database (the internal ID); username is what the person types to sign in
        conn.execute("CREATE TABLE IF NOT EXISTS users (user_id SERIAL PRIMARY KEY , username TEXT NOT NULL UNIQUE , password_hash TEXT NOT NULL)")
        # one row per uploaded file; the same content can't be uploaded twice by the same user
        conn.execute("CREATE TABLE IF NOT EXISTS documents (id SERIAL PRIMARY KEY , user_id INTEGER NOT NULL , filename TEXT , content_hash TEXT NOT NULL , UNIQUE (user_id , content_hash))")
        conn.execute("CREATE TABLE IF NOT EXISTS chunks (id SERIAL PRIMARY KEY , user_id INTEGER NOT NULL , document_id INTEGER REFERENCES documents(id) , chunk_text TEXT , chunk_vector vector(1024))")


def create_user(pool , username , password_hash) :
    # the UNIQUE constraint makes the "does this username exist" check and the insert ONE atomic step
    # (check-then-insert in two steps would let two simultaneous registrations both pass the check)
    with pool.connection() as conn :
        row = conn.execute("INSERT INTO users (username , password_hash) VALUES (%s,%s) ON CONFLICT (username) DO NOTHING RETURNING user_id",(username,password_hash)).fetchone()
    return row[0] if row else None  # None = this username was already taken, otherwise the new user_id


def get_user_by_username(pool , username) :
    with pool.connection() as conn :
        return conn.execute("SELECT user_id , password_hash FROM users WHERE username=%s",(username,)).fetchone()  # None = no such user


def hash_text(list_of_strings):
    joined_strings = " ".join(list_of_strings)  # seperator is # do not change or else ahshing chanes 
    encoded = joined_strings.encode("utf-8")
    hashed_content =  hashlib.sha256(encoded).hexdigest() 
    return hashed_content
